-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQge4BNy+BTnLkw0IG4
s3TGvwcTDXhFWc+hssuo/l8JiqygCgYIKoZIzj0DAQehRANCAATafz3T1BBxaTGb
LGLnjje5mGep5bWT/AlqI+1qJNerV4CBx6XvB/LifPfspLTOb5UIHQghPMIrsHzB
euVaH0UU
-----END PRIVATE KEY-----